version: "3"

services:
  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=tutorial-dev
      - POSTGRES_USER=vinhle
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
